version: "3.6"
services:
  db:
    image: postgres:latest
    ports:
      - "55432:5432"
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
